"""'添加账户确认状态'

Revision ID: 438caf028ca9
Revises: 6416f0d9bef1
Create Date: 2020-03-10 18:41:20.897672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438caf028ca9'
down_revision = '6416f0d9bef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
